### ISSUE TITLE
Ich schreib mal hier ;)

### ISSUE THREAD

**Issue by epicfail83** [LaggAt/LaggAt-Kodi#2]
Hallo LaggAt!

Ich poste das nun auch hier...hab dir aber auch ne PN auf kodi.tv geschickt ;)

Hab gesehn dass du das Audio Switcher Addon übernommen hast und hätte da direkt eine Frage an dich.

Derzeit nutze ich die Libreelec Dual Audio Builds....http://libreelec-dualaudio.subcarrier.de/
um das von mir gewünscht zu erreichen. 

Bei mir ist es leider so dass mein AVR noch kein HDMI Passthrough beherrscht im Standby...weshalb ich von meinem HTPC per HDMI an den TV gehe 
(um über den TV halt Filme und Serien zu schaun) und per SPDif geh ich an meinen AVR wenns denn mal etwas lauter sein soll. 

Dafür hab ich mir bei meiner Logitech Harmony 2 Aktionen gebaut....einmal mit TV Sound und einmal mit Sound vom AVR....sprich der TV wird auf stumm geschaltet und Ton kommt über SPDiF aus dem AVR.

Hoffe das ist verständlich. 

Das funktioniert auch wirklich super nur leider siehts so aus als würden die Dual Audio Builds wohl nicht weiter geführt weshalb ich am überlegen bin wieder auf das Audio Switcher Addon umzusteigen. Problem dabei ist, ich müsste dann jedesmal ne extra Tasten drücken um den richtigen Audio Output zu wählen...und seien wir mal ehrlich....der Mensch ist faul Big Grin und der WAF ist damit auch nicht mehr gegeben. 

Ich könnte natürlich die Taste für den Audio Switch natürlich in die jeweilige Aktion einbinden was sich aber wohl als schwierig gestaltet da mein NAS nicht ständig online ist und sich dieses beim start von Kodi erst startet....dauert, sagen wir mal 15 Sekunden. Wie gesagt, ich könnte die Taste mit einer Verzögerung von 15 Sekunden einbinden aber was ist wenn das NAS doch schon läuft? Dann müsste ich trotzdem die 15 Sekunden warten bis ich was machen muss und das ist nicht wirklich schön....

Jetzt die Frage an dich....könnte man sowas wie Dual Audio Output irgendwie mit deinem Addon realisieren? Oder hast du irgendeine Idee für mein Dilemma? Würde dann doch schön langsam gern auf Krypton umsteigen aber dieses Problem hindert mich halt noch daran. 

Sorry für den langen Text aber dir kann ich mein Problem wenigstens auf Deutsch schildern....Englisch ist ja doch etwas schwieriger Big Grin

Schöne Grüße aus dem wunderschönen Salzburgerland....woher kommst du?

Mike

**Comment by LaggAt** [comment]
Servus aus Tirol :)

Ich bin mir nicht sicher ob ich die Anforderung ganz verstehe - erst mal was ich glaube zu wissen...
- Du willst per Tastendruck den Audioausgang umschalten
- Du willst aber nicht nur Audioausgang, sondern auch NAS einschalten (WOL), nur solange warten wie nötig, irgendwas vom NAS abspielen oder so?
- Du brauchst ein Dual Audio Setup?

Ich denk Dir wird hier geholfen, wenn auch vielleicht nicht vollständig. Ich beschreib mal...

Drei konfigurierte Outputs:
- TV
- 2. Audio Ausgang( S/PDIF, was auch immer)
- kombinierter Audio Ausgang (realisiert mit zB http://kodi.wiki/view/PulseAudio#Combined_Output_aka_dual_audio)

Jetzt kommt das neue Plugin/Script EventProfiles ins Spiel:
Die Idee ist: Profile definieren, die im Prinzip aus einer Anzahl von Events entstehen. Event kann alles mögliche sein, Kodi spielt Audio, Tastendruk an einer Fernbedienung, ... das sollte ständig erweitert werden. Profile haben verschiedene Stati, im einfchsten Fall sind sie aktiv oder inaktiv.

Nehmen wir mal an Du möchtest beim Abspielen von Video auf das Combined Device umschalten:
Profil: "VideoProfile": aktiv wenn Kodi ein Video abspielt, Wieder inaktiv wenn kein Video abgespielt wird. EventProfiles startet dann Aktionen in anderen Plugins, in diesem Fall in einem neuen AudioSwitcher. 

Weiteres Beispiel: Per Tastendruck auf der Remote NAS starten (wenn nicht aktiv), wenn online Audio PartyModus über 2. Audio Output mit 25% Lautstärke. Etwas komplexer, aber möglich:
1. Profil: PartyMusicStart: wird aktiv per Taste auf Remote, inaktiv wenn Taste nochmal gedrückt wird.
Aktionen für dieses Profil: WOL an NAS, einschalten eines weiteren Profils PartyMusicStartPlaying
2. Profil: PartyMusicStartPlaying: sobald eingeschalten prüft es einen Event eines anderen Python skriptes, dass alle 500ms einen Netzwerkpfad prüft. Sobald dieser Zugreifbar ist schaltet dieses Profil ebenfalls aktiv und setzt die notwendigen weiteren Aktionen (Audiooutput, Lautstärke, Partymode, ...)

Idee ist eben, sämtliche Events - egal ob aus Kodi oder aus anderen Quellen - in Profile zu gruppieren, diese in Abhängigkeiten zu stellen und damit Aktionen zu steuern - quasi ein zentraler Controller für alle möglichen Plugins die folgen mögen. 

Habe ich etwas nicht abgedeckt?

P.s.: Der WAF ist das Wichtigste überhaupt, ohne den geht gar nichts. :p

**Comment by epicfail83** [comment]
Hi und danke für die Antwort....!!

Ob du das jetzt richtig verstanden hast bin ich mir nicht ganz sicher...vielleicht hab ichs aber auch nicht ganz begriffen. ;)

Mir gehts einfach darum dass dasselbe Audio Signal an beiden Ausgängen gleichzeitig anliegt....also HDMI und SPDiF zb....dann kann ich mit meinen bisherigen Harmony Profilen weiter machen. 
Problem an der Sache mit Audio Ausgang per Tastendruck selber umschalten is halt einfach das NAS welches nicht ständig online ist. Wie gesagt, dies wird ja bei Kodi start automatisch per Wol geweckt aber das dauert halt dann ne bestimmte Zeit.....

Ich schreib jetzt mal ein Beispiel warum dass mit dem Audio Switcher Addon zb nervig wäre:

Also ich starte mit der Harmony die Activity Kodi AVR
TV, HTPC, AVR werden gestartet
TV wird auf stumm geschalten
AVR auf den richtigen Input geschalten
HTPC startet NAS per WOL (dauert ca 10 Sekunden)
Nach diesen 10 Sekunden ist Kodi nun einsatzfähig und kann Befehle empfangen
Jetzt sendet die Harmony den Befehl senden das Audio Device auf SPDIF umzuschalten

Wär ansich kein Problem aber wenn das NAS nun schon vor dem Start der Activity online ist würds so laufen:
TV, HTPC, AVR werden gestartet
TV wird auf stumm geschalten
AVR auf den richtigen Input geschalten
HTPC sendet WOL und registriert das das NAS bereits online
Kodi ist nicht nach 10 Sekunden einsatzbereit sondern, sagen wir, nach 2 Sekunden
Jetzt kommt der Haken....die Harmony weiß das ja nicht und wartet trotzdem die von mir eingestellten 10 Sekunden und schaltet dann erst den Audio Ausgang auf SPDiF

Verstehst was ich meine? Das ist einfach Zeit die man warten muss bis man dann wirklich was machen kann mit dem HTPC....und das nervt halt richtig. Die Sekunden sind jetzt nur ungefähr Angaben....wie lang das genau alles dauert müsste ich erst ausloten. Darum ist mir der Dual Audio Output auch so wichtig....da isses dann wurscht wie lang was braucht weil ich den letzten Punkt in der Harmony Activity erst garnicht brauche....da ja eh auf beiden Audio Ausgängen dasselbe Signal anliegt. 

Aber so wie ich das verstanden habe ist so ein richtige gleichzeitiger Output an beiden Ausgängen mit deinem Addon leider auch nicht möglich oder?

Vielleicht denk ich auch irgendwie falsch und man kann das ganze ja doch irgendwie mit deinem Addon verwirklichen. 

Hoffe ich konnte dir das Szenario etwas besser erklären und noch mehr hoffe ich dass du mir helfen kannst.

**Comment by epicfail83** [comment]
Noch als Nachtrag.

Mein TV unterstützt leider kein DTS weshalb ich die Audioeinstellungen nicht einfach normal einstellen kann und deshalb bisher mit dem Dual Audio Patch gearbeitet hab.

**Comment by LaggAt** [comment]
Hat dein NAS einen Audioausgang?

**Comment by LaggAt** [comment]
Oder frag mer andersrum:
Wo läuft Kodi, was sind deine Ausgänge, und was möchtest überhaupt schalten? Aktuell glaub ich Du möchtest einfach immer auf beide Ausgänge abspielen - das wär dann ja ansich kein Kodi-Problem.

**Comment by epicfail83** [comment]
Kodi läuft auf nem HTPC....und ja ich bräuchte auf beiden Ausgängen (HDMI und SPDiF) gleichzeitig Audio. Die beiden Ausgänge müssen aber getrennt voneinander konfiguriert werden können da, wie gesagt mein TV kein DTS kann....

Oder eben mit so nem Addon wie deines die Audioprofile umschalten in der jeweiligen Harmony Aktion mit eingebunden. Da ist aber, eben das Problem mit den Timings....also wenn Nas läuft dann müsst ich ja trotzdem warten bis die Haromy mit der Aktion fertig ist. 

Ist etwas schwer zu erklären...hoffe so ists verständlicher

**Comment by LaggAt** [comment]
Stimmt, ich verstehs immer noch nicht :)
Da Du immer auf beiden Ausgängen abspielen willst weiß ich nicht was ich umschalten sollte. Das würd ich eher übers Linux lösen, sowas hier: http://askubuntu.com/questions/78174/play-sound-through-two-or-more-outputs-devices

Frag mer mal anders: auf welche Ereignisse exakt müsstest denn reagieren können?
Ich code jetzt mal nen Feiertag, vielleicht gibts dann was zum Testen :D

**Comment by epicfail83** [comment]
Eigentlich ist das ganze nicht so schwierig ;)

Sagen wir mal in konfiguriere Kodi normal....stell Passthrough über SPDiF ein und das mein AVR DTS kann dann ist es so dass wenn ich jetzt ohne AVR was schaue mit DTS Ton....dieser eben über den TV nicht ausgegeben werden kann da der dies einfach nicht unterstützt. Deshalb brauch ich 2 verschieden konfigurierte Audioausgänge wies eben der Dual Audio Patch macht. Oder ein Addon dass mir die Tonprofile umschaltet. 
Das mit dem Tonprofile umschalten wär, wie gesagt, kein Problem wenn da nicht die Wartezeit wäre die ich in der Harmony Aktion angeben muss (15 Sekunden oder so bis das Nas online ist) bis es diesen Befehl sendet. Diese 15 Sekunden muss ich aber auch warten wenn das Nas schon online ist...und das stört mich dann halt. ;)

Jetzt wo ich so genauer drüber nachdenk kannst du mir eigtl mit dem Addon auch ned wirklich helfen...ausser du kannst die beiden Audioausgänge gleichzeitig aktivieren ;)

Den Tipp von oben kann ich leider nicht anwenden...da ich Libreelec nutze.

Mit den .patch Files vom Dual Audio Projekt wirst du ja auch nichts anfangen können oder?

http://libreelec-dualaudio.subcarrier.de/patches/

**Comment by epicfail83** [comment]
Dieser User hat das ganz gut beschrieben....so ist es bei mir auch ;)

http://forum.kodi.tv/showthread.php?tid=295496

**Comment by LaggAt** [comment]
Ah ... Du machst den Dual Audio Ausgang IN Kodi, und nicht im System darunter :)
Wusst gar nit, dass es dafür was gibt.

Also wenn Du einfach nur etwas schalten musst nachdem das NAS online ist wird dir EventProfiles helfen. Ich kann jedoch nur schalten, was in Kodi, per anderem Plugin oder Script möglich ist. 

Da das Plugin gerade erst im entstehen ist und da die Netzwerkereignisse nicht ganz oben auf meiner Liste stehen wird das allerdings noch etwas dauern. Ich würd vorschlagen einfach mal beobachten was kommt :)

**Comment by epicfail83** [comment]
Ok, danke dir. Werd ich mich noch etwas gedulden mit dem Upgrade auf Krypton ;)

**Comment by LaggAt** [comment]
Passt, ich mach hier vorerst mal zu.
